---
version: 3

vars:
  BOOTC_IMAGE_TYPE: raw
  ROOTFS: xfs

tasks:
  bootc-image-builder:
    internal: true
    requires:
      vars: [IMAGE, BOOTC_IMAGE_TYPE, ARCH, OUTDIR, CONFIG, BASE_REPO]
    cmds:
      - cmd: mkdir -p ./{{.OUTDIR}}
      # - cmd: podman pull {{.BASE_REPO}}/{{.IMAGE}}
      - cmd: >
          podman run --rm -it --privileged
          --security-opt label=type:unconfined_t
          -v $(pwd)/{{.CONFIG}}:/config.toml:ro
          -v $(pwd)/{{.OUTDIR}}:/output
          -v /var/lib/containers/storage:/var/lib/containers/storage
          --pull=newer
          --platform linux/{{.ARCH}}
          quay.io/centos-bootc/bootc-image-builder:latest
          --target-arch {{.ARCH}}
          --type {{.BOOTC_IMAGE_TYPE}}
          --rootfs {{.ROOTFS}}
          {{.BASE_REPO}}/{{.IMAGE}}

  pi:
    cmd:
      task: bootc-image-builder
      vars:
        ARCH: aarch64
        IMAGE: pi
        ROOTFS: ext4
        OUTDIR: dist/pi
        CONFIG: variants/streampi/config.toml

  odroid-go-ultra:
    cmd:
      task: bootc-image-builder
      vars:
        ARCH: aarch64
        IMAGE: odroid-go-ultra
        ROOTFS: ext4
        OUTDIR: dist/odroid-go-ultra
        CONFIG: variants/odroid-go-ultra/config.toml

  odroid-go-ultra-complete:
    desc: Build complete OGU image with bootloader injected (ready to flash)
    deps: [odroid-go-ultra]
    cmds:
      - echo "Extracting bootloader from U-Boot container..."
      - mkdir -p /tmp/ogu-bootloader
      - cmd: |
          CONTAINER=$(podman create {{.BASE_REPO}}/odroid-go-ultra-uboot)
          podman cp $CONTAINER:/u-boot.bin.sd.bin /tmp/ogu-bootloader/u-boot.bin.sd.bin
          podman rm $CONTAINER
      - echo "Injecting bootloader at 1MB offset (sector 2048)..."
      - dd if=/tmp/ogu-bootloader/u-boot.bin.sd.bin of=dist/odroid-go-ultra/image/disk.raw conv=notrunc bs=512 seek=2048 status=progress
      - rm -rf /tmp/ogu-bootloader
      - echo "Complete flashable image ready at dist/odroid-go-ultra/image/disk.raw"

  pi-pr935:
    desc: Build Raspberry Pi disk image using bootupd PR #935 (test variant, Fedora 43)
    cmd:
      task: bootc-image-builder
      vars:
        ARCH: aarch64
        IMAGE: pi-pr935
        ROOTFS: ext4
        OUTDIR: dist/pi-pr935
        CONFIG: variants/pi-pr935/config.toml

