#!/bin/bash

if [[ $# -ge 2 ]]; then
    if [[ "$1" == "backend" && "$2" == "install" ]]; then
        # BASH_ARGV[0] is the last argument. In the case of bootupctl backend install, it's the path to the target
        # root directory.
        echo "Copying Raspberry Pi firmware files to ${BASH_ARGV[0]}/boot/efi/" >&2
        cp -av /usr/lib/bootc-raspi-firmwares/. "${BASH_ARGV[0]}"/boot/efi/
        echo "Copying Raspberry Pi firmware files finished" >&2

        # Add device tree overlay for USB gadget mode
        echo "Appending USB gadget settings to config.txt" >&2
        echo "dtoverlay=dwc2" | tee -a "${TARGET_ROOT}/boot/efi/config.txt" >&2
    fi
fi

exec /usr/bin/bootupctl-orig/bootupctl "$@"
