---
version: 3

tasks:
  build:
    internal: true
    requires:
      vars: [FILE, TAG, ARCH, FEDORA_MAJOR_VERSION, BASE_REPO]
    cmd: >
      podman build
      --platform linux/{{.ARCH}}
      --build-arg FEDORA_MAJOR_VERSION={{.FEDORA_MAJOR_VERSION}}
      --build-arg BASE_REPO={{.BASE_REPO}}
      -f {{.FILE}}
      -t {{.BASE_REPO}}/{{.TAG}}
      .

  pi:
    deps: []
    cmd:
      task: build
      vars:
        FILE: ./variants/pi/Containerfile
        TAG: pi

  odroid-go-ultra:
    deps: []
    cmd:
      task: build
      vars:
        FILE: ./variants/odroid-go-ultra/Containerfile
        TAG: odroid-go-ultra

  odroid-go-ultra-uboot:
    desc: Build U-Boot bootloader container for Odroid Go Ultra
    cmd:
      task: build
      vars:
        FILE: ./variants/odroid-go-ultra/Containerfile.uboot
        TAG: odroid-go-ultra-uboot

  odroid-go-ultra-simple:
    desc: Build Odroid Go Ultra using pre-built U-Boot container
    deps: [odroid-go-ultra-uboot]
    cmd:
      task: build
      vars:
        FILE: ./variants/odroid-go-ultra/Containerfile.simple
        TAG: odroid-go-ultra

  pi-pr935:
    desc: Build Raspberry Pi image using bootupd PR #935 (test variant, Fedora 43)
    deps: []
    cmd:
      task: build
      vars:
        FILE: ./variants/pi-pr935/Containerfile
        TAG: pi-pr935
        FEDORA_MAJOR_VERSION: 43
